name: Update_Model

on:
  schedule:
    - cron: '0 23 * * *' # Set your desired schedule (e.g., daily at midnight UTC)

jobs:
  update-model:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose the appropriate Python version

    - name: Commit and Push
      run: |
        git config user.email "jdominion123@gmail.com"
        git config user.name "DOMINION-JOHN1"
        git add .
        git commit -m "Update LSTM Model"
        git push
