name: Update_Model

on:
  schedule:
    - cron: "00 15 * * *"

jobs:
  update_model:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install yfinance  # Add this line to install yfinance

      - name: Update Model
        run: python update_model.py

      - name: Commit and Push
        run: |
          git config user.email "jdominion123@gmail.com"
          git config user.name "DOMINION-JOHN1"
          git add .
          git commit -m "Update LSTM Model"
          git remote add origin_with_token https://$GOLD_TOKEN@github.com/DOMINION-JOHN1/LSTM-Gold-Price-Prediction.git
          git push origin_with_token main
        env:
          PAT_TOKEN: ${{ secrets.GOLD_TOKEN }}
