name: Update_Model

on:
  schedule:
    - cron: "15 20 * * *"

jobs:
  update_model:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4  # Use the latest version of the action
    
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Use the latest version of the action
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version of the action
        with:
          python-version: '3.10'  # Use the latest available Python 3 version

      - name: Install Dependencies
        run: |
          python -m venv .venv
          . .venv/Scripts/activate
          pip install -r requirements.txt

      - name: Update Model
        run: python update_model.py

      - name: Commit and Push
        run: |
          git config user.email "jdominion123@gmail.com"
          git config user.name "DOMINION-JOHN1"
          git add .
          git commit -m "Update LSTM Model"
          git push
